packages:
  - "apps/**/**"
  - "packages/**/**"

overrides:
  js-yaml@3: "^3.15.2"
  js-yaml@4: "^4.3.2"
  shiki: 3.20.0
  svgo: 2.8.4
  ts-morph: 27.0.2

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "core-js"
  - "esbuild"
  - "lmdb"
  - "msgpackr-extract"
  - "protobufjs"
  - "sharp"
  - "unrs-resolver"
